name=FastLED
version=3.7.0
author=Daniel Garcia
maintainer=Daniel Garcia <dgarcia@fastled.io>
sentence=Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions (_no_fastled fork).
paragraph=Multi-platform library for controlling dozens of different types of LEDs along with optimized math, effect, and noise functions (_no_fastled fork).
category=Display
url=https://github.com/softhack007/FastLED
architectures=*
includes=FastLED.h
